image:
  name:
  pull_policy: IfNotPresent
resources:
  node_type: g5.48xlarge
  requests: {}
  limits: {}
tolerations: []
pvc:
  - name: pv-fsx
    mount_path: /fsx
  - name: pv-efs
    mount_path: /efs
ebs: {}
git:
  repo_url:
  branch:
  commit:
pre_script: []
post_script: []
server:
  name: generic-server 
  args: []
  command: []
  ports: []
  readiness_probe:
    period_secs: 5
    failure_threshold: 3
    path: /
    port: 
  startup_probe:
    period_secs: 10
    failure_threshold: 30
    path: /
    port: 
  liveness_probe:
    period_secs: 10
    failure_threshold: 3
    path: /
    port: 
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 4
      memory: 8Gi
  autoscaling:
    minReplicas: 1
    maxReplicas: 2
    metrics:
      - type: Pods
        pods:
          metric:
            name: cpu
          target:
            type: Utilization
            averageValue: 80
