---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tensorboard-controller-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tensorboard-controller-manager-role
subjects:
- kind: ServiceAccount
  name: tensorboard-controller-manager
  namespace: {{ .Values.kubeflow.namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tensorboard-controller-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tensorboard-controller-proxy-role
subjects:
- kind: ServiceAccount
  name: tensorboard-controller-manager
  namespace: {{ .Values.kubeflow.namespace }}
---