apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tensorboard-controller-leader-election-rolebinding
  namespace: {{ .Values.kubeflow.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tensorboard-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: tensorboard-controller-manager
  namespace: {{ .Values.kubeflow.namespace }}
