namespace: "karpenter"
role_name:
cluster_id:
consolidate_after: "600s"
capacity_type: "on-demand"
capacity_types:
  - "on-demand"
max_pods: 20

# ODCR Configuration
odcr:
  enabled: false
  neuron:
    ids: []
    tags: {}
  cuda:
    ids: []
    tags: {}
  cudaefa:
    ids: []
    tags: {}
