namespace: "karpenter"
role_name:
cluster_id:
consolidate_after: "600s"
capacity_type: "on-demand"
max_pods: 20

# Capacity Reservation Configuration (ODCR and Capacity Blocks for ML, cudaefa only)
cr:
  enabled: false
  cudaefa:
    capacity_types:
      - "on-demand"
    ids: []
    tags: {}
