global:
  namespace: kubeflow
maskrcnn:
  name: maskrcnn
  gpus: 8 
  gpus_per_node: 8
  image: # ECR image id 
  train_script: /tensorpack/examples/FasterRCNN/train.py
  shared_fs: efs
  shared_pvc: tensorpack-efs-gp-bursting
  data_dir: data
  steps_per_epoch: 15000  # Must be equal to 120000/gpus 
  lr_schedule: "[120000,160000,180000]"
  eval_period_in_epochs: 1
  data_train: "[\"train2017\"]"
  data_val: val2017
  mode_fpn: 'True'
  mode_mask: 'True'
  backbone_norm: FreezeBN
  backbone_weights: data/pretrained-models/ImageNet-R50-AlignPadding.npz
  image_pull_policy: IfNotPresent
  horovod_cycle_time: "0.5"
  horovod_fusion_threshold: "67108864"
  nccl_socket_ifname: ^lo,docker0 
  nccl_min_rings: 8
  nccl_debug: INFO
