apiVersion: kubeflow.org/v1alpha1
kind: MPIJob
metadata:
  name: {{ .Values.maskrcnn.name }}
  namespace: {{ .Values.global.namespace }} 
  labels:
    app.kubernetes.io/name: {{ .Values.maskrcnn.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  gpus: {{ .Values.maskrcnn.gpus }}
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: {{ .Values.global.shared_fs }} 
        persistentVolumeClaim:
            claimName: {{ .Values.global.shared_pvc }}
      - name: ebs
        hostPath:
            path: /ebs
            type: DirectoryOrCreate
      containers:
      - name: {{ .Values.maskrcnn.name }} 
        env:
        - name: HOROVOD_CYCLE_TIME
          value: "{{ .Values.maskrcnn.horovod_cycle_time }}" 
        - name: HOROVOD_FUSION_THRESHOLD
          value: "{{ .Values.maskrcnn.horovod_fusion_threshold }}" 
        - name: NCCL_SOCKET_IFNAME
          value: "{{ .Values.maskrcnn.nccl_socket_ifname }}" 
        - name: NCCL_MIN_NRINGS
          value: "{{ .Values.maskrcnn.nccl_min_rings }}" 
        - name: NCCL_DEBUG
          value: "{{ .Values.maskrcnn.nccl_debug }}" 
        - name: TENSORPACK_FP16 
          value: "{{ .Values.maskrcnn.tp_16 }}" 
        command: 
        - mpirun
        workingDir: {{ .Values.maskrcnn.working_dir }}
        args:
        - --output-filename 
        - /{{ .Values.global.shared_fs }}/{{ .Release.Name }}-{{ date "2006-01-02-15-04-05" .Release.Time  }}
        - --allow-run-as-root
        - --display-map
        - --tag-output
        - --timestamp-output
        - python3
        - {{ .Values.maskrcnn.train_script }} 
        - --logdir 
        - /{{ .Values.global.shared_fs }}/{{ .Release.Name }}-{{ date "2006-01-02-15-04-05" .Release.Time  }}/train_log/maskrcnn
        - --fp16
        - --images_per_epoch
        - "{{ .Values.maskrcnn.images_per_epoch }}"
        - --config  
        - MODE_MASK={{ .Values.maskrcnn.mode_fpn }}
        - MODE_FPN={{ .Values.maskrcnn.mode_mask }}
        - DATA.BASEDIR=/{{ .Values.maskrcnn.data_fs }}/{{ .Values.maskrcnn.data_dir }}
        - DATA.TRAIN={{ .Values.maskrcnn.data_train }} 
        - DATA.VAL={{ .Values.maskrcnn.data_val }}
        - TRAIN.BATCH_SIZE_PER_GPU={{ .Values.maskrcnn.batch_size_per_gpu }}
        - TRAIN.EVAL_PERIOD={{ .Values.maskrcnn.eval_period_in_epochs }}
        - TRAIN.LR_EPOCH_SCHEDULE={{ .Values.maskrcnn.lr_epoch_schedule }} 
        - BACKBONE.WEIGHTS=/{{ .Values.maskrcnn.data_fs }}/{{ .Values.maskrcnn.backbone_weights }}
        - BACKBONE.NORM={{ .Values.maskrcnn.backbone_norm }}
        - TRAINER=horovod
        - {{ .Values.maskrcnn.extra_config }}
        image: {{ .Values.maskrcnn.image }} 
        imagePullPolicy: {{ .Values.maskrcnn.image_pull_policy }}
        volumeMounts:
        - mountPath: /{{ .Values.global.shared_fs }}
          name: {{ .Values.global.shared_fs }}
        - mountPath: /ebs
          name: ebs
        resources:
          limits:
            nvidia.com/gpu: {{ .Values.maskrcnn.gpus_per_node }}
